version: "3"
services:
  streamlit-db-1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: streamlit
      MYSQL_DATABASE: streamlit
      MYSQL_USER: streamlit
      MYSQL_PASSWORD: streamlit
    volumes:
      - $PWD/mysql/:/var/lib/mysql
    networks:
      - mysql-st-crud
#phpmyadmin compose file
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - streamlit-db-1
    restart: always
    environment:
      PMA_HOST: streamlit-db-1
      PMA_USER: streamlit
      PMA_PASSWORD: streamlit
    ports:
      - "8013:80"
    networks:
      - mysql-st-crud
#streamlit compose file
  st-mysql-1:
    build: .
    restart: always
    container_name: st-mysql-1
    volumes:
      - $PWD:/app
    ports:
      - "5001:8501"
    networks:
      - mysql-st-crud

networks:
  mysql-st-crud:
